# Generated by Django 6.1 on 2026-08-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                choices=[
                    ("pickup", "Retiro en local"),
                    ("delivery", "Envío a domicilio"),
                ],
                default="pickup",
                max_length=20,
            ),
        ),
    ]
