# Generated by Django 6.1 on 2026-08-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_order_checkout_token_order_user_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: [
                setattr(item, "product_name", item.product.name) or item.save(update_fields=["product_name"])
                for item in apps.get_model("store", "OrderItem").objects.select_related("product").all()
            ],
            migrations.RunPython.noop,
        ),
    ]
