# Generated by Django 6.1 on 2026-08-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_orderitem_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zona de entrega",
                "verbose_name_plural": "Zonas de entrega",
                "ordering": ["cost"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.deliveryzone",
            ),
        ),
        migrations.CreateModel(
            name="ProductDeliveryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_delivery",
                    models.BooleanField(
                        default=True,
                        help_text="¿Permitir domicilio para este producto?",
                    ),
                ),
                (
                    "min_quantity_for_delivery",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Cantidad mínima de productos para permitir domicilio",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_config",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de entrega",
                "verbose_name_plural": "Configuraciones de entrega",
            },
        ),
    ]
