# Generated by Django 5.2.17 on 2026-09-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_bootstrap_admin_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductDeliveryConfig",
        ),
    ]
