# Generated by Django 5.2.17 on 2026-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_storeconfig_delivery_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Fecha")),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="Visitas"),
                ),
                (
                    "visitors",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visitantes únicos"
                    ),
                ),
                (
                    "seen_keys",
                    models.TextField(
                        default="[]",
                        help_text="Identificadores anónimos de visitantes ya contados en el día (JSON).",
                        verbose_name="Visitantes contados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de visitas",
                "verbose_name_plural": "Estadísticas de visitas",
                "ordering": ["-date"],
            },
        ),
    ]
