# Generated by Django 5.2.17 on 2026-09-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_dailystats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[(1, "Me gusta"), (-1, "No me gusta")],
                        verbose_name="Voto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
            ],
            options={
                "verbose_name": "Opinión del visitante",
                "verbose_name_plural": "Opiniones de visitantes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Visitante (hash)"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, default="", max_length=2, verbose_name="País (ISO)"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(auto_now=True, verbose_name="Detectado"),
                ),
            ],
            options={
                "verbose_name": "País del visitante",
                "verbose_name_plural": "Países de visitantes",
            },
        ),
    ]
