# Generated by Django 5.2.17 on 2026-09-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_feedback_visitorcountry"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="country_code",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="País (ISO)"
            ),
        ),
    ]
