# Generated by Django 5.2.17 on 2026-09-09 00:39

import json

from django.db import migrations, models


def backfill_seen_keys(apps, schema_editor):
    """Migra los visitantes únicos almacenados en JSON (seen_keys) a la
    tabla DailyVisitor antes de eliminar la columna."""
    DailyStats = apps.get_model("store", "DailyStats")
    DailyVisitor = apps.get_model("store", "DailyVisitor")
    created = 0
    for row in DailyStats.objects.exclude(seen_keys="[]").exclude(seen_keys=""):
        try:
            keys = json.loads(row.seen_keys)
        except (TypeError, ValueError):
            keys = []
        if not isinstance(keys, list):
            continue
        for key in keys:
            if key and isinstance(key, str) and len(key) <= 64:
                _, was_created = DailyVisitor.objects.get_or_create(
                    date=row.date, ip_hash=key
                )
                if was_created:
                    created += 1
    if created:
        print(f"DailyVisitor: {created} visitantes únicos backfilleados desde seen_keys")


def rebuild_seen_keys(apps, schema_editor):
    """Ruta inversa: reconstruye seen_keys (JSON) desde DailyVisitor."""
    DailyStats = apps.get_model("store", "DailyStats")
    DailyVisitor = apps.get_model("store", "DailyVisitor")
    for date in DailyVisitor.objects.order_by("date").values_list("date", flat=True).distinct():
        keys = list(
            DailyVisitor.objects.filter(date=date)
            .order_by("created_at")
            .values_list("ip_hash", flat=True)
        )
        DailyStats.objects.update_or_create(date=date, defaults={"seen_keys": json.dumps(keys)})


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_feedback_country_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Fecha")),
                (
                    "ip_hash",
                    models.CharField(max_length=64, verbose_name="Visitante (hash)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Registrado"),
                ),
            ],
            options={
                "verbose_name": "Visitante único diario",
                "verbose_name_plural": "Visitantes únicos diarios",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("date", "ip_hash")},
            },
        ),
        migrations.RunPython(backfill_seen_keys, rebuild_seen_keys),
        migrations.RemoveField(
            model_name="dailystats",
            name="seen_keys",
        ),
    ]